export const cardData = {
  Checkup: {
    image: require("../../assets/thumbnil.png"),
    isVideo: true,
    data: [
      {
        name: "Aiims",
        desc: "with cheese",
        price: 300,
        tag: "pizza",
        image: require("../../assets/aiims.jpg"),
      },
      {
        name: "Sir Ganga Ram",
        desc: "with strawberry",
        price: 530,
        tag: "cream",
        image: require("../../assets/ganga.jpg"),
      },
      {
        name: "RML",
        desc: "with cheese",
        price: 300,
        tag: "pizza",
        image: require("../../assets/rml.jpg"),
      },
      {
        name: "Safdarjung",
        desc: "with cheese",
        price: 450,
        tag: "burger",
        image: require("../../assets/safdarjung.jpg"),
      },
      {
        name: "LNGP",
        desc: "with cheese",
        price: 349,
        tag: "burger",
        image: require("../../assets/lnjp.jpg"),
      },
      {
        name: "Apollo",
        desc: "with mint",
        price: 450,
        tag: "drinks",
        image: require("../../assets/apollo.jpg"),
      },
      {
        name: "BLK-Max",
        desc: "with cheese",
        price: 600,
        tag: "sweets",
        image: require("../../assets/BLK-Max.jpeg"),
      },
      {
        name: "CK Birla",
        desc: "with mango",
        price: 180,
        tag: "cream",
        image: require("../../assets/ck-birla.jpg"),
      },
      {
        name: "Pant",
        desc: "with mint",
        price: 450,
        tag: "drinks",
        image: require("../../assets/pant.jpg"),
      },
      {
        name: "Jag Parvesh",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/japParvesh.jpg"),
      },
      {
        name: "Hindu Rao",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/hindu_rao.jpg"),
      },
      {
        name: "Sant Parmanand",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/sant.jpg"),
      },
    ],
  },
  generic: {
    image: require("../../assets/medicine.jpg"),
    data: [
      {
        name: "Aiims",
        desc: "with cheese",
        price: 300,
        tag: "pizza",
        image: require("../../assets/aiims.jpg"),
      },
      {
        name: "Sir Ganga Ram",
        desc: "with strawberry",
        price: 530,
        tag: "cream",
        image: require("../../assets/ganga.jpg"),
      },
      {
        name: "RML",
        desc: "with cheese",
        price: 300,
        tag: "pizza",
        image: require("../../assets/rml.jpg"),
      },
      {
        name: "Safdarjung",
        desc: "with cheese",
        price: 450,
        tag: "burger",
        image: require("../../assets/safdarjung.jpg"),
      },
      {
        name: "LNGP",
        desc: "with cheese",
        price: 349,
        tag: "burger",
        image: require("../../assets/lnjp.jpg"),
      },
      {
        name: "Apollo",
        desc: "with mint",
        price: 450,
        tag: "drinks",
        image: require("../../assets/apollo.jpg"),
      },
      {
        name: "BLK-Max",
        desc: "with cheese",
        price: 600,
        tag: "sweets",
        image: require("../../assets/BLK-Max.jpeg"),
      },
      {
        name: "CK Birla",
        desc: "with mango",
        price: 180,
        tag: "cream",
        image: require("../../assets/ck-birla.jpg"),
      },
      {
        name: "Pant",
        desc: "with mint",
        price: 450,
        tag: "drinks",
        image: require("../../assets/pant.jpg"),
      },
      {
        name: "Jag Parvesh",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/japParvesh.jpg"),
      },
      {
        name: "Hindu Rao",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/hindu_rao.jpg"),
      },
      {
        name: "Sant Parmanand",
        desc: "with cheese",
        price: 520,
        tag: "sweets",
        image: require("../../assets/sant.jpg"),
      },
    ],
  },
  Video: {
    image: require("../../assets/thumbnil.png"),
    isVideo: true,
    data: [
      {
        name: "5 Reasons You Are Drinking Water the Wrong Way",
        views: "403K",
        image: require("../../assets/thumbnail1.jpg"),
      },
      {
        name: "How to Cleanse Your Liver Naturally?",
        views: "403K",
        image: require("../../assets/thumbnail2.jpg"),
      },
      {
        name: "28 Signs Your Body is Deficient in Vital Nutrients (With Solution)",
        views: "403K",
        image: require("../../assets/thumbnail3.jpg"),
      },
      {
        name: "How to Purify Your Blood Naturally?",
        views: "403K",
        image: require("../../assets/thumbnail4.jpg"),
      },
      {
        name: "Cure Thyroid Problem Permanently in 4 Steps",
        views: "403K",
        image: require("../../assets/thumbnail5.jpg"),
      },
      {
        name: "5 Daily Foods You are Eating the Wrong Way",
        views: "403K",
        image: require("../../assets/thumbnail6.jpg"),
      },
      {
        name: "What Will Happen if You Quit Sugar for 21 Days (6 Healthy Alternatives)",
        views: "403K",
        image: require("../../assets/thumbnail7.jpg"),
      },
      {
        name: "Milk in India Ranked from Worst to Best",
        views: "403K",
        image: require("../../assets/thumbnail8.jpg"),
      },
      {
        name: "20 Soaps in India Ranked from Worst to Best",
        views: "403K",
        image: require("../../assets/thumbnail9.jpg"),
      },
      {
        name: "Ayurvedic Diet Plan for Extreme Fat Loss (Healthy & Effective)",
        views: "403K",
        image: require("../../assets/thumbnail10.jpg"),
      },
    ],
  }
};

export const tagsData = [
  {
    name: "Checkup",
    key: "Checkup",
    icon: require("../../assets/checkUp.png"),
  },
  {
    name: "Generic",
    key: "generic",
    icon: require("../../assets/genericMedicine.png"),
  },
  {
    name: "Test",
    key: "labTest",
    icon: require("../../assets/labTest.png"),
  },
  {
    name: "Care",
    key: "careTaker",
    icon: require("../../assets/careTaker.png"),
  },
  {
    name: "Video",
    key: "Video",
    icon: require("../../assets/healthyVideo.png"),
  },
];

export const departmentList = [
  {
    name: "General",
    desc: "Infections, chronic diseases, and preventive care.",
    tag: "pizza",
    image: require("../../assets/checkup.jpg"),
  },
  {
    name: "Gynecology",
    desc: "Pregnancy, childbirth, and women's reproductive health.",
    tag: "cream",
    image: require("../../assets/gynecology.png"),
  },
  {
    name: "Pediatrics",
    desc: "Health and medical care of children",
    tag: "cream",
    image: require("../../assets/Pediatrics.jpeg"),
  },
  {
    name: "Surgery",
    desc: "General surgery, orthopedic surgery, cardiovascular surgery, neurosurgery, and more.",
    tag: "cream",
    image: require("../../assets/surgery.png"),
  },
  {
    name: "Anesthesiology",
    desc: "Managing pain during surgical procedures or medical interventions.",
    tag: "cream",
    image: require("../../assets/anesthesiology.jpeg"),
  },
  {
    name: "Radiology",
    desc: "X-rays, CT scans, MRI scans, ultrasound, and other imaging modalities.",
    tag: "cream",
    image: require("../../assets/radiology.jpg"),
  },
  {
    name: "Ophthalmology",
    desc: "Health of the eye",
    tag: "cream",
    image: require("../../assets/ophthalmology.jpeg"),
  },
  {
    name: "Dermatology",
    desc: "Skin, hair, and nails, including acne, psoriasis, and skin cancer.",
    tag: "cream",
    image: require("../../assets/skin.jpeg"),
  },
  {
    name: "Cardiology",
    desc: "Heart diseases and conditions",
    tag: "cream",
    image: require("../../assets/cardiology.jpeg"),
  },
];
