export const cardData = [
  {
    name: "Pizza 1",
    desc: "with cheese",
    price: 300,
    tag: "pizza",
    image: require("../../assets/pizza.jpeg"),
  },
  {
    name: "Ice-cream",
    desc: "with strawberry",
    price: 530,
    tag: "cream",
    image: require("../../assets/cream3.jpeg"),
  },
  {
    name: "Jalebi",
    desc: "with cheese",
    price: 600,
    tag: "sweets",
    image: require("../../assets/sweet.jpeg"),
  },
  {
    name: "Burger 1",
    desc: "with cheese",
    price: 450,
    tag: "burger",
    image: require("../../assets/burger4.jpeg"),
  },
  {
    name: "Mango Shake",
    desc: "with mint",
    price: 450,
    tag: "drinks",
    image: require("../../assets/drink.jpeg"),
  },
  {
    name: "Ice-cream",
    desc: "with mango",
    price: 180,
    tag: "cream",
    image: require("../../assets/cream1.jpeg"),
  },
  {
    name: "Pizza 2",
    desc: "with cheese",
    price: 300,
    tag: "pizza",
    image: require("../../assets/pizza2.jpeg"),
  },
  {
    name: "Burger 2",
    desc: "with cheese",
    price: 349,
    tag: "burger",
    image: require("../../assets/burger2.jpeg"),
  },
  {
    name: "Strawberry",
    desc: "with mint",
    price: 450,
    tag: "drinks",
    image: require("../../assets/drink2.jpeg"),
  },
  {
    name: "Gajar Halwa",
    desc: "with cheese",
    price: 520,
    tag: "sweets",
    image: require("../../assets/sweet7.jpeg"),
  },
  {
    name: "Pizza 3",
    desc: "with cheese",
    price: 550,
    tag: "pizza",
    image: require("../../assets/pizza3.jpeg"),
  },
  {
    name: "Gulab Jamun",
    desc: "with cheese",
    price: 80,
    tag: "sweets",
    image: require("../../assets/sweet2.jpeg"),
  },
  {
    name: "Strawberry",
    desc: "with mint",
    price: 450,
    tag: "drinks",
    image: require("../../assets/drink3.jpeg"),
  },
  {
    name: "Rasgulla",
    desc: "with cheese",
    price: 100,
    tag: "sweets",
    image: require("../../assets/sweet3.jpeg"),
  },

  {
    name: "Ice-cream",
    desc: "with chocolate",
    price: 60,
    tag: "cream",
    image: require("../../assets/cream.jpeg"),
  },
  {
    name: "Pizza 4",
    desc: "with cheese",
    price: 400,
    tag: "pizza",
    image: require("../../assets/pizza4.jpeg"),
  },
  {
    name: "Burger 3",
    desc: "with cheese",
    price: 200,
    tag: "burger",
    image: require("../../assets/burger3.jpeg"),
  },
  {
    name: "Kaju Katli",
    desc: "with cheese",
    price: 700,
    tag: "sweets",
    image: require("../../assets/sweet4.jpeg"),
  },
  {
    name: "Ladoo",
    desc: "with cheese",
    price: 250,
    tag: "sweets",
    image: require("../../assets/sweet5.jpeg"),
  },
  {
    name: "Burger 5",
    desc: "with cheese",
    price: 399,
    tag: "burger",
    image: require("../../assets/burger5.jpeg"),
  },
  {
    name: "Ice-cream",
    desc: "with butter scotch",
    price: 120,
    tag: "cream",
    image: require("../../assets/cream2.jpeg"),
  },
  {
    name: "Besan Ladoo",
    desc: "with cheese",
    price: 220,
    tag: "sweets",
    image: require("../../assets/sweet6.jpeg"),
  },
  {
    name: "Ras Malai",
    desc: "with cheese",
    price: 300,
    tag: "sweets",
    image: require("../../assets/sweet8.jpeg"),
  },
  {
    name: "Burger 4",
    desc: "with cheese",
    price: 299,
    tag: "burger",
    image: require("../../assets/burger.jpeg"),
  },
];

export const tagsData = [
  {
    name: "All Menu",
    key: "all",
    icon: require("../../assets/fastFood.png"),
  },
  {
    name: "Pizza",
    key: "pizza",
    icon: require("../../assets/pizza.png"),
  },
  {
    name: "Burger",
    key: "burger",
    icon: require("../../assets/burger.png"),
  },
  {
    name: "Drinks",
    key: "drinks",
    icon: require("../../assets/soda.png"),
  },
  {
    name: "Sweets",
    key: "sweets",
    icon: require("../../assets/sweet.png"),
  },
  {
    name: "Ice-cream",
    key: "cream",
    icon: require("../../assets/cream.png"),
  },
];
